# Generated by Django 5.1.1 on 2024-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnineapp", "0002_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tractor_number", models.CharField(max_length=20, unique=True)),
                ("rc_date", models.DateField()),
            ],
        ),
    ]
