# Generated by Django 5.1.1 on 2024-10-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnineapp", "0005_tractorhours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_load", models.FloatField()),
                ("load_rate", models.FloatField()),
                ("load_amount", models.FloatField()),
                ("description", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vnineapp.customer",
                    ),
                ),
                (
                    "tractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vnineapp.tractor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loading_charge", models.FloatField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vnineapp.employee",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_jobs",
                        to="vnineapp.job",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "employee")},
            },
        ),
    ]
