# Generated by Django 5.1.1 on 2024-10-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnineapp", "0006_job_employeejob"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeejob",
            unique_together=set(),
        ),
    ]
