# Generated by Django 5.1.1 on 2024-10-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnineapp", "0007_alter_employeejob_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
