# Generated by Django 5.1.1 on 2024-10-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnineapp", "0010_sale"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
