# Generated by Django 5.1.1 on 2024-10-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnineapp", "0012_ledger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ledger",
        ),
    ]
